#import "/research/lib/template.typ": *

// First real-world-circuit measurement in the zkmcu arc. The VK + proof are
// not synthetic arkworks-generated bytes, they come from the production
// Semaphore trusted setup and snarkjs pipeline. Companion to the phase-2.6
// BLS12-381 results report; complementary rather than overlapping, since
// Semaphore is BN254.

#show: paper.with(
  title: "Semaphore depth-10 Groth16 on RP2350: real-world-circuit baseline",
  authors: ("zkmcu",),
  date: "2026-04-22",
  kind: "report",
  abstract: [
    First measurement of a production-shaped Groth16 circuit on the
    RP2350 at 150 MHz. VK + proof come from
    [Semaphore v4.14.2](https://semaphore.pse.dev) (Merkle tree depth 10,
    4 public inputs) under the CDN-hosted trusted setup, generated by
    `@semaphore-protocol/proof` via `snarkjs.groth16.fullProve`. Same
    bytes the Ethereum Semaphore verifier precompile accepts.
    *Measured verify time: #strong("1 176 ms") on Cortex-M33,
    #strong("1 564 ms") on Hazard3 RV32.* Iteration-to-iteration
    variance *#strong("0.030 %")* on both cores — tightest of any
    measurement in this project. Predictions written down ahead of
    time (+1 160 ms M33 / +1 620 ms RV32) were within 1.4 % and
    3.5 % of measured; this is the closest prediction-measurement
    match of the phase-2 arc.
  ],
)

= Setup

- *Hardware.* Raspberry Pi Pico 2 W (RP2350, ARM Cortex-M33 @ 150 MHz
  and Hazard3 RV32 @ 150 MHz; 520 KB SRAM).
- *Verifier.* `zkmcu-verifier` 0.1.0, `no_std`, EIP-197 wire format,
  `substrate-bn` 0.6 as the crypto backend. Unchanged from earlier
  phase-2.0–2.6 runs.
- *Firmware.* `bench-rp2350-m33` / `bench-rp2350-rv32`, extended in
  commit `5aeadb9` to bench the Semaphore vector alongside `square` +
  `squares-5`.
- *Vector provenance.* VK from `vendor/semaphore/packages/proof/src/
  verification-keys.json` (depth 10 slice). Proof from
  `scripts/gen-semaphore-proof/` running
  `@semaphore-protocol/proof` 4.14.2 under
  `snark-artifacts` tag 4.13.0. Deterministic under the hardcoded
  seed `"zkmcu-bench-seed"` + message `"zkmcu-bench-message"` +
  scope `"zkmcu-bench-scope"`, so the vector is byte-identical on
  every regeneration.
- *Toolchain.* `rustc 1.94.1`, `release` profile with `lto = "fat"`,
  `opt-level = "s"`, `codegen-units = 1`, `panic = "abort"`.
- *Measurement.* `DWT::cycle_count` on Cortex-M33, `mcycle` on
  Hazard3 (with `mcountinhibit` unmasked at boot per phase-0 finding).

= Results

== Cortex-M33 Semaphore verify

#compare-table(
  ("Quantity", "Value"),
  (
    ([cycles median (5 iterations)], [176 475 754]),
    ([cycles min],                   [176 450 089]),
    ([cycles max],                   [176 503 682]),
    ([us median],                    [1 176 505]),
    ([ms median],                    [*1 176 ms*]),
    ([iteration-to-iteration variance], [*0.030 %*]),
    ([result],                       [`ok=true` on every iteration]),
  ),
)

Companion measurements from the same firmware flash (for
same-build comparison rather than run-to-run drift concerns):

#compare-table(
  ("Circuit", "M33 verify median", "Public inputs"),
  (
    ([square (synthetic)], [962 ms], [1 small-integer]),
    ([squares-5 (synthetic)], [974 ms], [5 small-integers (< 2#super[13])]),
    ([*Semaphore depth-10*], [*1 176 ms*], [*4 full-width 254-bit scalars*]),
  ),
)

== Hazard3 RV32 Semaphore verify

#compare-table(
  ("Quantity", "Value"),
  (
    ([cycles median (6 iterations)], [234 701 189]),
    ([cycles min],                   [234 681 740]),
    ([cycles max],                   [234 752 298]),
    ([us median],                    [1 564 674]),
    ([ms median],                    [*1 564 ms*]),
    ([iteration-to-iteration variance], [*0.030 %*]),
    ([result],                       [`ok=true` on every iteration]),
  ),
)

Companion square run from the same firmware flash: 1 327 ms median.

= Prediction check

The response-budget prediction, committed ahead of measurement in
the 2026-04-22 session notes:

#compare-table(
  ("Quantity", "Predicted", "Measured", "Δ"),
  (
    ([M33 Semaphore verify], [\~1 160 ms], [1 176 ms], [*+1.4 %*]),
    ([RV32 Semaphore verify], [\~1 620 ms], [1 564 ms], [*−3.5 %*]),
  ),
)

Both within the stated uncertainty. The M33 prediction model was:

$ "verify" = "base (1 pub)" + n_"extra" × "cost per big-scalar input" $

with `base = 962 ms` and `cost = ~67 ms`; Semaphore has `n_extra = 3`,
giving predicted `962 + 3 × 67 = 1 163 ms`. Measured per-extra-input
cost came out at **71 ms**, so the linear model held to within noise.
This is the closest-to-prediction result of the phase-2 arc.

= Cross-regime comparison

Per-public-input cost depends strongly on scalar Hamming weight
because `substrate-bn`'s sliding-window NAF short-circuits on
small scalars (most NAF windows become zero and get skipped):

#compare-table(
  ("Regime", "M33 cost per extra input", "Circuit that hits this"),
  (
    ([small-integer scalars (< 2#super[13])], [\~3 ms], [`squares-5` synthetic]),
    ([big-scalar (254-bit, random-ish)], [*\~71 ms*], [Semaphore, Tornado Cash, MACI, Aztec, ...]),
  ),
)

*24× gap between the two regimes.* Any production circuit with
public inputs shaped like "a merkle root", "a nullifier", "a
keccak-or-poseidon hash" hits the big-scalar side.

Consequence for circuit designers targeting embedded Groth16
verify on BN254: minimize public-input count aggressively, fold
multiple logical inputs into one hash-commitment `Fr` if at all
possible. Going from 5 public inputs to 1 on a big-scalar circuit
saves roughly 300 ms of on-device verify time on Cortex-M33.

= Cross-ISA ratio: independent confirmation of phase-2.6 finding

Phase-2.6's BLS12-381 results report found that the "Hazard3 beats
Cortex-M33 on G1 scalar mul" result from BN254 did not generalize to
BLS12-381, and attributed the flip to Cortex-M33's `UMAAL` winning
at BLS12's larger field size. The Semaphore measurement provides an
*independent* datapoint testing a different face of the same
argument: on BN254 (where RV32 *does* win on G1 mul), adding more
G1 scalar muls to the verify path should pull RV32 proportionally
closer to M33.

#compare-table(
  ("Circuit", "RV32 / M33 verify ratio"),
  (
    ([square (BN254, 1 small-integer public input)], [1.38×]),
    ([*Semaphore depth-10 (BN254, 4 big-scalar public inputs)*], [*1.33×*]),
  ),
)

Ratio tightens by 0.05 — small but consistent with the scaling
prediction. Not a falsification event, an *intensification*: the
phase-2.6 cross-ISA argument is not just a BLS12 story, it governs
circuit-shape-dependent cross-curve/cross-core behaviour in general.

= Measurement stability

The 0.030 % variance on both cores over 5-6 iterations is the
tightest recorded in this project:

#compare-table(
  ("Run", "Iteration-to-iteration variance"),
  (
    ([BN254 Groth16 baseline (M33)], [0.065 %]),
    ([BLS12-381 baseline (M33)], [0.064 %]),
    ([BLS12-381 baseline (RV32)], [0.043 %]),
    ([*Semaphore baseline (M33 and RV32)*], [*0.030 %*]),
  ),
)

Single-tenant, fixed-clock, in-order-execution silicon makes the
RP2350 a measurement-friendly target by nature. Still worth noting
that the Semaphore firmware's 3-vector boot pass (square, squares-5,
semaphore) gives the USB-CDC stack longer to settle before the main
loop begins, wich may be reducing a small jitter component that
was present in earlier 2-vector runs.

= What is new in this report

Relative to the phase-2.0 through phase-2.6 coverage:

- First measurement of a vector *not* generated by our own
  `zkmcu-host-gen` tool. VK + proof came from outside our codebase.
- First verification of a circuit deployed on Ethereum (the Semaphore
  precompile exists on mainnet; the VK we used is the one it checks
  against at depth 10).
- First datapoint in the *big-scalar public-input* regime that
  existing runs hadn't exercised.
- First measurement to fall inside the prediction band on first
  shot (phase-2.6 had two of three predictions fire falsification
  criteria).

= Non-claims

- No claim that every Semaphore-shaped circuit will verify in exactly
  1 176 ms. Tree depth affects witness size, not VK or public-input
  count — but a firmware implementing the `pairing_batch` sum the
  same way would land on the same timing profile.
- No claim that `zkmcu-verifier` is the fastest no_std BN254
  verifier possible. The per-extra-input cost of 71 ms on M33 is a
  `substrate-bn` property, not a lower bound on pairing-grade G1
  scalar mul with `UMAAL` intrinsics in play.
- No claim that Semaphore is particularly optimised for embedded
  verification. The circuit was designed for Ethereum L1 verification
  and happens to be well-sized for our embedded target; a custom
  embedded-first circuit could be cheaper (smaller nPublic, hash
  folding, etc).

= Reproduction

```bash
# One-time setup.
git submodule update --init
cd scripts/gen-semaphore-proof && bun install && bun run gen
cd ../..
cargo run -p zkmcu-host-gen --release -- semaphore \
    --depth 10 --proof scripts/gen-semaphore-proof/proof.json
cargo test -p zkmcu-verifier --release --test parse_semaphore

# Flash + measure (per core).
cargo build -p bench-rp2350-m33 --release
scp target/thumbv8m.main-none-eabihf/release/bench-rp2350-m33 \
    pid-admin@10.42.0.30:/tmp/bench-m33.elf
# Pi 5, Pico in BOOTSEL:
picotool load -v -x -t elf /tmp/bench-m33.elf
cat /dev/ttyACM0
```

Raw TOMLs and serial logs: `benchmarks/runs/
2026-04-22-{m33,rv32}-semaphore-depth10/`.
