//! Sanity check that the Semaphore-depth-10 VK extracted from the
//! `vendor/semaphore` submodule by `zkmcu-host-gen semaphore` parses
//! cleanly through `zkmcu-verifier`. This is a no-proof test — we only
//! verify the VK decodes on-curve, not that verify runs, because we
//! don't have a proof committed yet (Semaphore proofs require their
//! snarkjs toolchain, see phase-2.7 notes).

#![allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::single_match_else,
    clippy::print_stderr,
    clippy::doc_markdown
)]

use std::fs;
use std::path::PathBuf;

use zkmcu_verifier::{parse_proof, parse_public, parse_vk, verify};

fn semaphore_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("zkmcu-vectors")
        .join("data")
        .join("semaphore-depth-10")
}

#[test]
fn semaphore_depth_10_vk_parses() {
    let path = semaphore_dir().join("vk.bin");
    // Semaphore VK is regenerated from the submodule via
    //   cargo run -p zkmcu-host-gen --release -- semaphore
    // If it's missing locally (e.g. submodule not initialised), skip rather
    // than fail CI.
    let Ok(bytes) = fs::read(&path) else {
        eprintln!("skipping: {} not present", path.display());
        return;
    };
    let vk = parse_vk(&bytes).expect("Semaphore depth-10 VK parses");
    assert_eq!(
        vk.ic.len(),
        5,
        "Semaphore depth-10 VK should have 5 IC points (nPublic=4 + 1)"
    );
}

/// The full end-to-end check: committed Semaphore VK + proof + public inputs
/// must produce `Ok(true)` from `zkmcu-verifier::verify`. Proof + public are
/// produced by `scripts/gen-semaphore-proof/gen.ts` + the Rust-side importer
/// in `zkmcu-host-gen semaphore --proof ...`. Only runs if those .bin files
/// are present.
///
/// This is the whole grant-pitch moment: a real Semaphore Groth16 proof that
/// was generated by snarkjs under the production trusted setup, verifying
/// through our no_std verifier.
#[test]
fn semaphore_depth_10_proof_verifies() {
    let dir = semaphore_dir();
    let vk_path = dir.join("vk.bin");
    let proof_path = dir.join("proof.bin");
    let public_path = dir.join("public.bin");

    if !proof_path.exists() || !public_path.exists() {
        eprintln!(
            "skipping: {} and/or {} not present",
            proof_path.display(),
            public_path.display()
        );
        return;
    }

    let vk = parse_vk(&fs::read(&vk_path).unwrap()).expect("parse vk");
    let proof = parse_proof(&fs::read(&proof_path).unwrap()).expect("parse proof");
    let public = parse_public(&fs::read(&public_path).unwrap()).expect("parse public");

    assert_eq!(public.len(), 4, "Semaphore has 4 public inputs");

    let ok = verify(&vk, &proof, &public).expect("verify runs");
    assert!(
        ok,
        "zkmcu-verifier rejected a genuine Semaphore Groth16 proof — \
         likely a wire-format mismatch (Fp2 order, Fr endianness, or the \
         public-input order disagrees with snarkjs)."
    );
}
