//! Constant-time dual-hash PQ-Semaphore verify path (Phase H).
//!
//! Sibling of [`crate::pq_semaphore_dual`]. Same dual-hash semantics
//! (Poseidon2-`BabyBear` ∧ Blake3 over the shared public-input blob),
//! same heap-drop pattern, but a different *timing contract*: every
//! input takes the same wall-clock time to produce a yes/no answer,
//! within ε.
//!
//! ## Scope: macro-scale, not instruction-level
//!
//! "Macro-scale" means total verify duration is independent of mutation
//! class — a remote attacker who can only observe wall-clock time
//! (e.g. through USB CDC-ACM responses) cannot distinguish a
//! parse-fail from a Merkle-fail from an honest accept. This is
//! sufficient against a network-side adversary with millisecond
//! resolution.
//!
//! "Instruction-level" CT — every `BabyBear` add and Poseidon2 round
//! branch-free on secrets — is **out of scope**. Defending against an
//! attacker with cycle-resolved on-chip probing requires per-line
//! review of the vendored Plonky3 code and is tracked separately.
//!
//! ## Deployment guidance
//!
//! Both [`verify_constant_time`] (this module) and
//! [`crate::pq_semaphore_dual::parse_and_verify`] are public API. They
//! solve different problems:
//!
//! - **`verify_constant_time`** for personal hardware tokens, FIDO-class
//!   devices, signing oracles — anything where attacker-controlled
//!   probing of reject latency is in the threat model. Every probe
//!   costs the attacker a full ~1.6 s verify; the timing oracle from
//!   `parse_and_verify`'s fast-fail path is closed.
//! - **`parse_and_verify`** for relay endpoints, public-facing
//!   verifiers, anything where `DoS` resistance dominates and the
//!   worst reject is a few-ms parse fail. Phase C numbers measured
//!   the reject medians (M0 8.5 ms, M5 127 ms vs honest 1611 ms).
//!
//! ## How CT is enforced
//!
//! Both legs always run to completion, regardless of whether the
//! incoming bytes parse:
//!
//! - Errors collapse into `false` via `r1 & r2` (bitwise, **not**
//!   short-circuit `&&`) so neither leg can be skipped.
//! - When real input fails to parse, a static canonical fallback
//!   (the committed `pq-semaphore-d10-dual` proof) is parsed instead
//!   so the verify path runs on placeholder data of the right shape.
//!   The fallback is independent of the attacker-controlled `data`,
//!   eliminating second-order leakage.
//! - The Poseidon2 leg is parsed + verified inside an inner block so
//!   `Proof`, `Config`, and `Air` drop before the Blake3 leg parses.
//!   Peak heap is `max(p2_peak, b3_peak)`, identical to
//!   [`crate::pq_semaphore_dual::parse_and_verify`].
//!
//! Verify itself is the dominant cost (~ 800 ms per leg on M33), so
//! the few microseconds of variance in the parse-fail path stay well
//! inside the macro-CT budget (±0.5 % × 1611 ms ≈ 8 ms).
//!
//! ## Two-stage entry points (for benchmarks with large proofs)
//!
//! [`verify_constant_time`] takes raw bytes and keeps them alive for
//! the whole call (~1.6 s). For an attacker-facing deployment that's
//! the right shape — one call, one CT envelope. For the **ct-reject
//! benchmark**, it's a memory problem: the caller wants to mutate the
//! proof bytes per iteration, which means a heap `Vec`, and 169 KB of
//! `Vec` plus the verifier's ~304 KB peak doesn't fit in the 384 KB
//! firmware heap.
//!
//! The two-stage helpers split parse from verify:
//!
//! - [`parse_p2_constant_time`] / [`parse_b3_constant_time`] /
//!   [`parse_public_constant_time`] — always return a shape-valid
//!   parsed value (real, or the static fallback if parse failed) plus
//!   a `bool` recording whether the input itself parsed.
//! - [`verify_p2_leg_constant_time`] / [`verify_b3_leg_constant_time`]
//!   — always run the leg's verifier to completion against the parsed
//!   inputs.
//!
//! The bench composes them with explicit `drop`s so the raw bytes and
//! the p2 parsed proof free *before* the next allocation. Heap peak
//! stays at ~304 KB (same as the one-stage path on static refs).
//!
//! These helpers are **not** the right shape for adversary-facing use
//! — composing them only delivers macro-CT if the caller runs both
//! legs every time and combines results bitwise. Production code
//! should keep using [`verify_constant_time`].

use crate::pq_semaphore;
use crate::pq_semaphore_blake3;

/// Parsed public-inputs, shared across both verifier legs.
pub type Public = [pq_semaphore::Val; pq_semaphore::NUM_PUBLIC_INPUTS];

/// Canonical Poseidon2-leg proof — the committed `pq-semaphore-d10-dual`
/// vector. Used as a static fallback when attacker-supplied bytes fail
/// `parse_proof`, so the verify path runs on shape-valid data either
/// way. Regenerated by `just regen-vectors`; the
/// `ct_fallback_p2_parses_and_verifies` test in
/// `tests/pq_semaphore_dual_ct.rs` asserts canonicality.
static FALLBACK_PROOF_P2: &[u8] =
    include_bytes!("../../zkmcu-vectors/data/pq-semaphore-d10-dual/proof_p2.bin");

/// Canonical Blake3-leg proof; mirror of [`FALLBACK_PROOF_P2`] for the
/// Blake3 leg.
static FALLBACK_PROOF_B3: &[u8] =
    include_bytes!("../../zkmcu-vectors/data/pq-semaphore-d10-dual/proof_b3.bin");

/// Canonical 96-byte public-input blob; fallback for `parse_public_inputs`.
static FALLBACK_PUBLIC: &[u8] =
    include_bytes!("../../zkmcu-vectors/data/pq-semaphore-d10-dual/public.bin");

/// Parse the Poseidon2-leg proof bytes; substitute the static fallback
/// on parse failure. Returned `bool` is `true` iff `bytes` itself
/// parsed.
///
/// The returned `Proof` is owned and does not borrow from `bytes`, so
/// the caller may drop the input after this returns.
#[must_use]
pub fn parse_p2_constant_time(bytes: &[u8]) -> (pq_semaphore::Proof, bool) {
    let parse = pq_semaphore::parse_proof(bytes);
    let ok = parse.is_ok();
    let proof = parse.unwrap_or_else(|_| {
        pq_semaphore::parse_proof(FALLBACK_PROOF_P2)
            .expect("FALLBACK_PROOF_P2 is the committed canonical proof")
    });
    (proof, ok)
}

/// Parse the Blake3-leg proof bytes; substitute the static fallback on
/// parse failure. Returned `bool` is `true` iff `bytes` itself parsed.
///
/// The returned `Proof` is owned and does not borrow from `bytes`, so
/// the caller may drop the input after this returns.
#[must_use]
pub fn parse_b3_constant_time(bytes: &[u8]) -> (pq_semaphore_blake3::Proof, bool) {
    let parse = pq_semaphore_blake3::parse_proof(bytes);
    let ok = parse.is_ok();
    let proof = parse.unwrap_or_else(|_| {
        pq_semaphore_blake3::parse_proof(FALLBACK_PROOF_B3)
            .expect("FALLBACK_PROOF_B3 is the committed canonical proof")
    });
    (proof, ok)
}

/// Parse the public-inputs blob; substitute the canonical 96-byte
/// fallback on parse failure. Returned `bool` is `true` iff `bytes`
/// itself parsed.
pub fn parse_public_constant_time(bytes: &[u8]) -> (Public, bool) {
    let parse = pq_semaphore::parse_public_inputs(bytes);
    let ok = parse.is_ok();
    let public = parse.unwrap_or_else(|_| {
        pq_semaphore::parse_public_inputs(FALLBACK_PUBLIC)
            .expect("FALLBACK_PUBLIC is the committed canonical blob")
    });
    (public, ok)
}

/// Verify the Poseidon2 leg against a pre-parsed proof + public. Always
/// runs to completion; returns `true` iff the leg accepts.
///
/// Dispatches to [`pq_semaphore::verify_with_config_rtc`], which closes the
/// M5-class public-input timing oracle that the upstream
/// `p3-uni-stark::verify` exposes via early-return on Merkle / `PoW` /
/// `FinalPoly` failures inside FRI.
#[must_use]
pub fn verify_p2_leg_constant_time(proof: &pq_semaphore::Proof, public: &Public) -> bool {
    let config = pq_semaphore::make_config();
    let air = pq_semaphore::build_air();
    pq_semaphore::verify_with_config_rtc(proof, public, &config, &air).is_ok()
}

/// Verify the Blake3 leg against a pre-parsed proof + public. Always
/// runs to completion; returns `true` iff the leg accepts.
///
/// Dispatches to [`pq_semaphore_blake3::verify_with_config_rtc`].
#[must_use]
pub fn verify_b3_leg_constant_time(proof: &pq_semaphore_blake3::Proof, public: &Public) -> bool {
    let config = pq_semaphore_blake3::make_config();
    let air = pq_semaphore_blake3::build_blake3_air();
    pq_semaphore_blake3::verify_with_config_rtc(proof, public, &config, &air).is_ok()
}

/// Constant-time dual-hash verify: returns `true` iff both legs accept.
///
/// Always runs both legs to completion, regardless of whether parsing
/// succeeds. See module-level docs for the threat model and the
/// macro-vs-instruction-level CT scope boundary.
///
/// Heap usage is identical to [`crate::pq_semaphore_dual::parse_and_verify`]
/// (peak = `max(p2_peak, b3_peak)`, ~ 304 KB measured Phase B).
#[must_use]
#[allow(clippy::similar_names)]
pub fn verify_constant_time(
    proof_p2_bytes: &[u8],
    proof_b3_bytes: &[u8],
    public_bytes: &[u8],
) -> bool {
    let (public, public_ok) = parse_public_constant_time(public_bytes);

    let r1 = {
        let (proof, parse_ok) = parse_p2_constant_time(proof_p2_bytes);
        verify_p2_leg_constant_time(&proof, &public) & parse_ok
    };

    let r2 = {
        let (proof, parse_ok) = parse_b3_constant_time(proof_b3_bytes);
        verify_b3_leg_constant_time(&proof, &public) & parse_ok
    };

    public_ok & r1 & r2
}
