//! Host-side sanity check that the committed Fibonacci STARK proof round-
//! trips through `zkmcu-verifier-stark`. Same shape as
//! `zkmcu-verifier/tests/parse_semaphore.rs`: skips cleanly if the bytes
//! aren't present locally (e.g. in a fresh clone before `just regen-vectors`
//! has run), passes if both parse + verify succeed.
//!
//! This is the phase 3.1.2 equivalent of "does the whole chain hang
//! together on host before we put it on hardware."

#![allow(
    clippy::unwrap_used,
    clippy::panic,
    clippy::single_match_else,
    clippy::print_stderr,
    clippy::doc_markdown
)]

use std::fs;
use std::path::PathBuf;

use zkmcu_verifier_stark::{fibonacci, parse_proof};

fn stark_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("zkmcu-vectors")
        .join("data")
        .join("stark-fib-1024")
}

#[test]
fn fibonacci_1024_proof_verifies() {
    let dir = stark_dir();
    let proof_path = dir.join("proof.bin");
    let public_path = dir.join("public.bin");

    // Regenerate via: cargo run -p zkmcu-host-gen --release -- stark
    let Ok(proof_bytes) = fs::read(&proof_path) else {
        eprintln!("skipping: {} not present", proof_path.display());
        return;
    };
    let public_bytes = fs::read(&public_path).expect("public.bin should exist if proof.bin does");

    let proof = parse_proof(&proof_bytes).expect("parse proof");
    let public = fibonacci::parse_public(&public_bytes).expect("parse public");

    // This is the grant-pitch moment for phase 3.1: a real STARK proof,
    // generated by winter-prover, verified through zkmcu-verifier-stark's
    // no_std wrapper. If it fails here on host it'll fail on the MCU too,
    // so this test acts as the gate before the firmware bench.
    fibonacci::verify(proof, public).expect("STARK verify returned Ok(()) on host");
}
